/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 */

package com.patriotnative;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

public abstract class NativePatriotNativeSpec extends ReactContextBaseJavaModule implements TurboModule {

  public static final String NAME = "PatriotNative";

  public NativePatriotNativeSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void installWatchface(String packageName, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getConnectedDevices(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isAppInstalledOnWatch(String packageName, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void sendMessageToWatch(String nodeId, String path, String data, Promise promise);
}
